### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by amulettneo** [PINTO0309/onnxruntime4raspberrypi#1]
hello,

When I install the runtime 1.9.1 and numpy=1.21.4 
but I got error when I import onnxruntime:

>>> import onnxruntime
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an error set

**Comment by PINTO0309** [comment]
```
pip install -U numpy
```

**Comment by amulettneo** [comment]
but numpy 1.21.6 need compile，can you share the whl of numpy,THANKS.   I stared. 👍
